### ISSUE TITLE
Account for spaces in roll method

### ISSUE THREAD

**Issue by NotAnNPC** [dsibilly/jinx-the-robot#1]
".roll 3d6 + 0 + 0" returning as invalid roll.

**Comment by dsibilly** [comment]
Looks like [roll](https://github.com/troygoode/node-roll) doesn't like infix spaces around operands in a dice roll query. Easy to fix.

Resolved in _150abd2_, scheduled for v0.2.3 release.

**Comment by dsibilly** [comment]
v0.2.3 is released. Closing as fixed.
